### PR TITLE
fixed index page numbers

### PR DESCRIPTION
**Pull request by Calciumcarbonate321**
The cogs name list started from 2 in the index page, I made a small fix for it.
The main file was shown as "No Category" in the help command, so I made a small fix for it.

### CODE REVIEW

**Comment by Calciumcarbonate321** [comment]
image

**Comment by CircuitSacul** [comment]
"No Category" is the name used by the built-in help command, since commands in "No Category" don't have a cog.

Also, cog numbering starts from 2 because it's supposed to reflect the page number the cog is on, not the cog number. See #39 and #38

**Comment by Calciumcarbonate321** [comment]
Well, it does look a bit awkward for the numbering starting from 2, you are saying that it is the page number

**Comment by CircuitSacul** [comment]
I personally agree, but it seems @stroupbslayen prefers it this way. It might be best to make it an option, though.

**Comment by Calciumcarbonate321** [comment]
Regarding the "no category" thing, only the makn file is named as "no category", since it isn't am extension. Any other file that you use in your bot and contains commands will be a cog, the cog names are present in the index page already. Also if you create cogs within your main file also, they will be considered as seperate cogs by the pretty help package. So having that as "Main cog" would seem more apt.

**Comment by stroupbslayen** [comment]
I'm going to close this and try to think of a different way to do address the concern. The issue has been brought up enough times that it's worth looking into. Thank you for your input though.

**Pull request closed without merging**
