### PR TITLE
Use `raw_reaction_add` instead of `reaction_add` to avoid unresponsive paginators when the original message is no longer cached

### PR DESCRIPTION
**Pull request by CircuitSacul**
I have a fairly large bot (around 700 servers at this point) and I've been running into a problem with disputils and this library. The paginator works fine at first, but after about 20 seconds it becomes unresponsive. The reason for this is because `reaction_add` requires the message to be cached, and after 20 seconds a large bot can easily get 1k messages (the limit of the default message cache). An easy solution to this is to use `raw_reaction_add` instead, and it has no performance impact at all.

### CODE REVIEW

**Comment by stroupbslayen** [comment]
Does this change still work with bot custom and default emojis?

**Comment by CircuitSacul** [comment]
I didn't think to check, I'll check that real quick.

**Comment by CircuitSacul** [comment]
@stroupbslayen it does now

**Comment by stroupbslayen** [comment]
Great, thanks @CircuitSacul !

**Pull request merged**
